# Site settings
title: Rodrigo Dumont
header-img: img/home-bg.jpg
email: rodrigo@rxdx.com.br
copyright_name: Rodrigo Dumont
description: "Nothing but rxdx website!"
baseurl: ""
url: "http://rxdx.com.br"
twitter_username: rodrigox
github_username:  rxdx
facebook_username:  rodrigodumont
instagram_username: dreadrodz
email_username:  rodrigo@rxdx.com.br

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
